n = input('digite um algo:')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É maiúsculo?', n.isupper())
print('É alafanumerico?', n.isalnum())